### ISSUE TITLE
Maintain a milestone

### ISSUE THREAD

**Issue by GeorgeS2019** [OblivCode/pycs#4]
### PyCs Modules
- [ ] [datetime](https://docs.python.org/3/library/datetime.html)
- [ ] [pathlib](https://docs.python.org/3/library/pathlib.html)
- [ ] [zipfile](https://docs.python.org/3/library/zipfile.html)
- [ ] [io](https://docs.python.org/3/library/io.html)
